Feature/buttons
m3ntorship/pickly-playground pull request #17
Opened 2021-01-06 23:53 UTC by omarawad0

i have added the buttons section, form and tabs

2021-01-06 23:56 UTC, Nilegfx commented
this is not a review but just an overall comment.

Your commits are too granular (too mnay commits), try to combine them into set of workable commit.

2021-01-07 00:12 UTC, omarawad0 commented
Okay i will try.

2021-01-07 02:53 UTC, seifeldeen3388 requested changes
Great attention to detail. But please consider the following:
- Adding focus state styles for the buttons.
- Making the entire radio button clickable, not just the little circles.
- Improving the dimensions of the radio button circle fill in.
- Last, you have deleted most, if not all, of the classes added by Kareem to the file `buttonswithTW.css`, probably while resolving a conflict. Please find them and paste them back in.

2021-01-07 02:53 UTC, seifeldeen3388 commented on tailwind.config.js
> +        24: '0.24',
Please revise the need for all of these values.
For example, the lengths of input fields don't have to be exactly as the design of atom, the lengths might change when put in context, molecules and organisms.
Also, some of these already exist in tailwind, like `8rem` and `2rem`. We are only extending here so they are still there.

2021-01-07 18:27 UTC, seifeldeen3388 approved these changes
LGTM

2021-01-07 18:36 UTC, merged